import { Router } from "express";
import {
  getAllDailyReports,
  getMyDailyReports,
  getArchivedReports,
  getDailyReportById,
  createDailyReport,
  updateDailyReport,
  deleteDailyReport,
  createAutoGeneratedReport,
  generateUnifiedReport,
  getUnifiedDailyReports,
  getUnifiedDailyReportById,
} from "../controllers/dailyReportController";
import {
  getLabWorkstationsForReport,
  saveWorkstationChecklist,
  getWorkstationChecklist,
} from "../controllers/workstationReportController";
import {
  getAllProcedures,
  getReportProcedures,
  saveReportProcedures,
  getWorkstationProcedures,
} from "../controllers/proceduresController";
import { authenticateToken, requireRole } from "../middleware/auth";
import { auditMiddleware } from '../middleware/audit';

const router = Router();

router.use(authenticateToken);

// Standard Reports
router.get("/", getAllDailyReports);
router.get("/my", getMyDailyReports);
router.get("/archived", getArchivedReports);
router.get("/:id", getDailyReportById);
router.post("/", auditMiddleware("CREATE", "daily report"), createDailyReport);
router.post("/auto-generated", auditMiddleware("CREATE", "auto-generated daily report"), createAutoGeneratedReport);
router.post("/generate-unified", auditMiddleware("CREATE", "unified daily report"), generateUnifiedReport);
router.put("/:id", auditMiddleware("UPDATE", "daily report"), updateDailyReport);
router.delete("/:id", requireRole(["Admin"]), auditMiddleware("DELETE", "daily report"), deleteDailyReport);

// Unified Reports (combines auto_complaints and auto_forms)
router.get("/unified/list", getUnifiedDailyReports);
router.get("/unified/:id", getUnifiedDailyReportById);

// Workstation Checklists inside Reports
router.get("/:id/workstations", getWorkstationChecklist);
router.post("/:id/workstations", saveWorkstationChecklist);
router.get("/utils/lab-workstations", getLabWorkstationsForReport); // Changed path slightly to avoid collision

// Procedures inside Reports
router.get("/utils/all-procedures", getAllProcedures);
router.get("/:id/procedures", getReportProcedures);
router.post("/:id/procedures", saveReportProcedures);
router.get("/utils/workstation-procedures", getWorkstationProcedures);

export default router;
